# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1ab4d02fb5d7f2e3938aa7d5c97aecb72e67f073f66315e3c5310a09bbcca1c8fd6b99c6b7b053ec6eb2b6d1d8a1e2c76087f8b6df55b8b48a499a3a1cafda32

test:
  secret_key_base: 08040a82a3a1f593fda4496cb5aa904bda7069f3452eb6292e41147bbc466cf6d550acf32616542c19e823b47ff5e3d12edbcf4f3c7bc015a3c3e76ff114e506

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
